#Project Euler Problem 2
#
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

import sys
sys.path.insert(0, '/Users/brianroper/Documents/github/math')

from fibonacci import fibonacci

n = 4000000

fib_list = fibonacci(n,method="max")


total = 0

for number in fib_list:
    if number%2 == 0:
        total += number

print total
